#!/usr/bin/env bash
#
# Author Cesar Herdenez <caherdenez@gmail.com>


# Vars

ROOT_DIR=$(cd "$(dirname "$0")"; pwd) # absolute path



puts-step() {
	echo -e "\e[1m\e[36m===> $@\e[0m"
}

puts-error() {
	echo -e "\e[1m\e[31m=!=> $@\e[0m"
}

puts-warn() {
	echo -e "\e[1m\e[33m=!=> $@\e[0m"
}

print() {
	echo -e "\e[1m\e[35m===> $@\e[0m"
}
